version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - url=${PROD}
    volumes:
      - .:/app
    command: poetry run pytest --alluredir=allure-results