name: Docker Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run Docker Compose
      run: docker-compose up --build -d

    - name: Run tests in Docker
      env:
        PROD: ${{ secrets.PROD }}
      run: docker-compose exec app pytest --alluredir=allure-results

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-results
#
#    - name: Send notification to email
#      uses: dawidd6/action-send-mail@v3
#      with:
#        connection_url: ${{ secrets.MAIL_CONNECTION }}
#        subject: GitHub Actions Test Results
#        to: user@example.com
#        from: 'GitHub Actions <actions@example.com>'
#        body: The tests have completed. Check the Allure report for details.
#        attachments: allure-results